In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset = pd.read_csv('insurance_pre.csv')

In [7]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [11]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [13]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [15]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=dataset[['charges']]

In [17]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [19]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [21]:
#split into training set and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train) #fit=calculation and transform peform calculation and provide results
x_test=sc.transform(x_test)

In [23]:
x_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

In [27]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf',C=100000)

In [29]:
regressor.fit(x_train,y_train)

C:\Users\alkar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000)

In [30]:
y_pred=regressor.predict(x_test)

In [31]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [35]:
r_score

0.872956195555764

In [37]:
import pickle
filenm="final_model_svm.sav"

In [39]:
pickle.dump(regressor,open(filenm,'wb'))

In [41]:
filesc="sdsc.sav"

In [43]:
pickle.dump(sc,open(filesc,'wb'))

In [45]:
preip=sc.transform([[19, 1, 27.9, 0, 0]])

C:\Users\alkar\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [47]:
preip

array([[-1.46814257, -4.80180845, 22.31352362, -0.98885138, -0.49929923]])

In [49]:
lo_model=pickle.load(open("final_model_svm.sav",'rb'))
result=lo_model.predict(preip)

In [51]:
result

array([19357.43828326])